### ISSUE TITLE
Collections which are not set, will be null in toArray

### ISSUE THREAD

**Issue by LDSign** [dereuromark/cakephp-dto#17]
Hi Mark

Really like your plugin and the possibilities DTOs create.

Though, I have a minor issue and hope you can help, me:

The result from toArray() is:

```
Array
(
    [Var1] => A
    [List1] => Array
        (
            [0] => Array
                (
                    [Var2] => B
                    [List2] => Array
                        (
                            [0] => Array
                                (
                                    [Var3] => C
                                    [Var4] => D
                                    [Var5] => E
                                    [Var6] => F
                                )
                        )
                    [List3] => 
                )
        )
)
```

I have never set or instantiated "List3". Is it possible to avoid the "null" appearance in the result? Of course, I could just cleanup the result, but that feels wrong.

Thanks,
Frank

**Comment by dereuromark** [comment]
whats your Definition of this dto? it sure should be possible to get an empty array.

**Comment by LDSign** [comment]
```
<?xml version="1.0"?>
<dtos
	xmlns="cakephp-dto"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="cakephp-dto https://github.com/dereuromark/cakephp-dto">

	<dto name="Test">
		<field name="Var1" type="int" />
		<field name="ProduktList" type="Product[]" collection="true"  required="false" />
	</dto>

	<dto name="Produkt">
		<field name="Var2" type="string" />
	</dto>
</dtos>
```

This is not the definition like the constructed example above, but it leads to the same issue. In this case "ProductList" appears in the array, although it was not set in the app.

**Comment by dereuromark** [comment]
What do u expect? That the key is not set at all? Then touchedToArray() etc might be useful.

**Comment by LDSign** [comment]
Yes thats exactly what I expect. Ive tried touchedToArray(), but so I cannot get feilds which have default values :(

**Comment by dereuromark** [comment]
Is it a problem that your array contains the keys of the null ones?
I would probably just ignore them in there if I was you.

Do you have any idea how we can make your expectation wórk without removing any of the current use cases?

**Comment by LDSign** [comment]
Yes, unfortunatley this is a problem, because the data goes to an api which does not expect that the key exists :(

I have not looked at your plugin code yet. But I will have look at it tomorrow (its rainy in germany ;)).

Just came to a next issue: The required attribute does not work at all in my case. After setting the value, there is still an exception that the required field is missing.

**Comment by dereuromark** [comment]
Well, where I am in Germany, the sun is shining right now ;) Inbetween some rain once in a while

If this is a default value then the other side of toArray() could also know about it. Or you pass all and ignore null values.

How does your require statement in the DTO look like? And how do you use it?
Required is mainly useful with immutable, as it makes sure those are intantiated completely as full and valid ones. With mutable ones I am not sure what the use case is, other than not having an nullable setter/getter.

**Comment by dereuromark** [comment]
As for your original issue:

I agree that the collection should be an array here.
Instead of
```
array:2 [▼
  "Var1" => 1
  "ProductList" => null
]
```
then
```
array:2 [▼
  "Var1" => 1
  "ProductList" => []
]
```

**Comment by dereuromark** [comment]
I opened a PR to fix the collection toArray part :)

**Comment by LDSign** [comment]
Thanks Mark. But I think its better to avoid presenting the key at all if it is not set...it just makes more sense, because its not set ;)

For now, Ive extended the Hash-Class with an filterNull method. Works but feels not right ;)

Regarding the "required"-issue your arguments are correct. There is not a real use case. But Ive expected that toArray() will check required fields too and not only the method instantiation).
