### ISSUE TITLE
“Precision” attribute for floatvals

### ISSUE THREAD

**Issue by LDSign** [dereuromark/cakephp-dto#19]
Hi

How about an attribute to add “precision” to floatvals? This could result in a rounding call in the generated Dto method.

Just needed this for currency values for convienience, but I am not sure if this is too much logic for a Dto. What do you think?

Frank

**Comment by dereuromark** [comment]
I think we should keep it agnostic.
This is where you would use a concrete value object here instead, which could handle this all internally.

**Comment by asaliev** [comment]
@LDSign I think that's outside of the scope of DTOs.

Also I wouldn't recommend using floats for currency values. Have a look at something like https://github.com/moneyphp/money
