### ISSUE TITLE
Callable fields

### ISSUE THREAD

**Issue by tbelknapsgs** [dereuromark/cakephp-dto#44]
I'm probably missing something. But how did you intend callable fields to be implemented? I'd love to be able to include some basic data-handling functions in my Dtos, this seems like the right place for it. For example, I have a MessageDto and an AddressDto that gets inserted into the fields for recipients, senders, copies, blind copies. It would be nice to be able to quickly transform the AddressDto into a Mailer-acceptible array of ['name' => 'emailaddress'] with a Collection call inside a function to keep it DRY. 

Thanks for any direction you can provide. Cheers as ever!

**Comment by dereuromark** [comment]
You want to have `type="callable"` ?

Given the recent discussions about callable rather to be used as Closure - and changes like https://github.com/cakephp/cakephp/pull/15853 - it seems that the Closure is maybe a better fit here, no?

But feel free to implement this otherwise - via PR.
