### ISSUE TITLE
Union types

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-dto#9]
Do we want to support union types: `string|int`/`string|int[]` etc?
Currently one would just use `mixed`. But it could be easily added.
```xml
<field name="value" type="string|int" />
<field name="attributes" type="string|int[]" />
```
Maynly a semantic/browser/phpstan issue, as currently this would just be
```xml
<field name="value" type="mixed" />
<field name="attributes" type="array" />
```

**Comment by asaliev** [comment]
This is definitely something we should do. I'm all for stricter typing.

**Comment by dereuromark** [comment]
So what kind of union types would be allowed then? Any number (2, 3, 4), any type?
Or do we just do scalar ones?

- 'int', 'float', 'string', 'bool', 'callable'
- object, iterable in PHP7.1/7.2

I feel like more than 3 types at once makes no sense, then you could have just as well kept the mixed one.
And any other type then throws generation exception, as well.

**Comment by asaliev** [comment]
> So what kind of union types would be allowed then? Any number (2, 3, 4), any type?
I feel like limiting the number of types is a bit too much, considering that the use case for union types could be an external datasource which the developer has no control of.

**Comment by dereuromark** [comment]
That's fair.

**Comment by asaliev** [comment]
> Or do we just do scalar ones?
> - 'int', 'float', 'string', 'bool', 'callable'
> - object, iterable in PHP7.1/7.2

Yeah, I think that limiting to 'simple types' is more than enough
